<?php

declare(strict_types=1);

namespace MoneroIntegrations\MoneroRpc\WalletRpc;

use MoneroIntegrations\MoneroRpc\Model\Address;
use MoneroIntegrations\MoneroRpc\Request\ParameterInterface;
use MoneroIntegrations\MoneroRpc\Request\RpcRequest;
use Square\Pjson\Json;
use MoneroIntegrations\MoneroRpc\Trait\JsonSerializeBigInt;
use Square\Pjson\JsonDataSerializable;

/**
 * Verify a signature on a string.
 */
class VerifyRequest implements ParameterInterface, JsonDataSerializable
{
    use JsonSerializeBigInt;

    /**
     * What should have been signed.
     */
    #[Json]
    public string $data;

    /**
     * Public address of the wallet used to `sign` the data.
     */
    #[Json]
    public Address $address;

    /**
     * signature generated by `sign` method.
     */
    #[Json]
    public string $signature;

    public static function create(string $data, Address $address, string $signature): RpcRequest
    {
        $self = new self();
        $self->data = $data;
        $self->address = $address;
        $self->signature = $signature;
        return new RpcRequest('verify', $self);
    }
}
