on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        monero: [ 0.18.0.0, 0.18.1.2 ]
        php: [8.1, 8.2]
        dependency-version: [prefer-lowest, prefer-stable]

    name: Tests P${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }} - monero ${{ matrix.monero }}

    steps:
      - uses: actions/checkout@v3

      - name: Spin up containers
        run: docker-compose -f tests/docker-compose.yml up -d
        env:
          MONERO_VERSION: ${{ matrix.monero }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Test formatting
        run: composer test:lint

      - name: Unit Tests
        run: composer test:unit

      - name: Integration Tests
        run: composer test:integration
